robot:
  - name: link_0
    order: 0
    mesh: base.dae

  - name: link_1
    order: 1
    translate: [0.0, 0.0, 0.1519]
    rotate: [0, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [0.0, 0.0, 0.0]
    rotateLink: [0, 0, 0]
    mesh: shoulder.dae

  - name: link_2
    order: 2
    translate: [0.0, ${shoulder_offset}, 0]
    rotate: [0, 1.5708, 0]
    angleAxis: [0, 1, 0]
    translateLink: [ 0.0, 0.0, ${-ur3_a2/2.0} ]
    rotateLink: [ 0, 0, 0 ]
    mesh: upperarm.dae

  - name: link_3
    order: 3
    translate: [0, ${elbow_offset}, ${upper_arm_length}]
    rotate: [0.0, 0.0, 0.0]
    angleAxis: [0, 1, 0]
    translateLink: [ 0.0, 0.0, ${-ur3_a3/2.0} ]
    rotateLink: [ 0, 0, 0 ]
    mesh: forearm.dae

  - name: link_4
    order: 4
    translate: [0.0, 0.0, ${forearm_length}]
    rotate: [0.0, 1.5708, 0]
    angleAxis: [0, 1, 0]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: wrist1.dae

  - name: link_5
    order: 5
    translate: [0.0, ${wrist_1_length}, 0.0]
    rotate: [-1.5708, 0, 0.0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0]
    rotateLink: [ 0, 0, 0 ]
    mesh: wrist2.dae

  - name: link_6
    order: 6
    translate: [0.0, 0.0, ${wrist_2_length}]
    rotate: [0, 0, 0]
    angleAxis: [0, 1, 0]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: wrist3.dae