# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import robot_command_pb2 as robot__command__pb2
import robot_state_pb2 as robot__state__pb2
import robot_info_pb2 as robot__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13robot_service.proto\x12\x05rocos\x1a\x13robot_command.proto\x1a\x11robot_state.proto\x1a\x10robot_info.proto2\xee\x01\n\x0cRobotService\x12\x44\n\rReadRobotInfo\x12\x17.rocos.RobotInfoRequest\x1a\x18.rocos.RobotInfoResponse\"\x00\x12G\n\x0eReadRobotState\x12\x18.rocos.RobotStateRequest\x1a\x19.rocos.RobotStateResponse\"\x00\x12O\n\x12WriteRobotCommmand\x12\x1a.rocos.RobotCommandRequest\x1a\x1b.rocos.RobotCommandResponse\"\x00\x42\x13\x42\x11RobotServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\021RobotServiceProto'
  _globals['_ROBOTSERVICE']._serialized_start=89
  _globals['_ROBOTSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
