robot:
  - name: link_0
    order: 0
    mesh: base_link.STL

  - name: link_1
    order: 1
    translate: [0.0, 0.0, 0.1215]
    rotate: [0, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [0.0, 0.0, 0.0]
    rotateLink: [0, 0, 0]
    mesh: link_1.STL

  - name: link_2
    order: 2
    translate: [0.0, -0.1225, 0]
    rotate: [1.5708, -1.5708, 0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: link_2.STL

  - name: link_3
    order: 3
    translate: [0.3, 0.0, 0.0]
    rotate: [3.1416, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: link_3.STL

  - name: link_4
    order: 4
    translate: [0.276, 0.0, 0.012] # 模型值是0.276，实际应为0.210
    rotate: [3.1416, 0, 1.5708]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: link_4.STL

  - name: link_5
    order: 5
    translate: [0.0, 0.09, 0.0]
    rotate: [-1.5708, 0.0, 0.0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0]
    rotateLink: [ 0, 0, 0 ]
    mesh: link_5.STL

  - name: link_6
    order: 6
    translate: [0.0, -0.082, 0.0]
    rotate: [1.5708, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: link_6.STL

